import { Translation, Language } from "./types";

export const TRANSLATIONS: Record<Language, Translation> = {
	en: {
		welcome: "Welcome to Respira",
		onboarding_q1: "How many cigarettes do you smoke per day?",
		onboarding_q2: "How much does a pack cost?",
		onboarding_q3: "How many cigarettes are in a pack?",
		onboarding_q4:
			"What is your biggest dream/goal to achieve with the saved money?",
		onboarding_q5: "How much does this dream cost?",
		onboarding_dream_placeholder:
			"e.g. A trip to Japan, a new electric guitar...",
		onboarding_dream_cost_placeholder: "Approximate cost",
		cta_start: "Start Journey",
		cta_next: "Next",
		dashboard_title: "Your Progress",
		money_saved: "Money Saved",
		cigs_not_smoked: "Cigarettes Avoided",
		time_passed: "Time Smoke-Free",
		dream_progress: "Progress towards your dream",
		craving_button: "I have a craving!",
		craving_loading: "Analyzing your strength...",
		craving_modal_title: "Wait! Read this first...",
		days: "Days",
		hours: "h",
		minutes: "m",
		seconds: "s",
		congrats: "You are doing great!",
		history_chart: "Savings Forecast (30 Days)",
		lapsed_button: "I've smoked",
		lapse_modal_title: "It's just a stumble",
		lapse_modal_text:
			"Don't be hard on yourself. A lapse is not a failure. Remember your dream: {dream}. It's still there waiting for you. Shall we reset the clock and keep going?",
		lapse_confirm: "Yes, let's restart",
		lapse_cancel: "Nevermind",
		auth_register_title: "Create Account",
		auth_login_title: "Login",
		auth_email: "Email",
		auth_password: "Password",
		auth_have_account: "Already have an account? Login",
		auth_no_account: "New here? Start your journey",
		auth_login_btn: "Login",
		auth_register_btn: "Register & Save Progress",
		auth_error_not_found: "Account not found or wrong password.",
		auth_error_exists: "An account with this email already exists.",
		auth_save_progress: "Save your progress to reach your dream",
		logout: "Logout",
		// New keys
		urge_modal_title: "How strong is the urge?",
		urge_rating_label: "Rate from 1 to 10",
		urge_low_title: "It's just boredom",
		urge_low_text:
			"You don't need it. The craving will pass in 10 minutes. Let's wait together.",
		urge_high_title: "High Alert ⚠️",
		urge_high_text:
			"If you smoke this, it costs you {cost} and pushes '{dream}' further away.",
		urge_btn_analyze: "Analyze Urge",
		urge_btn_resisted: "I Resisted!",
		urge_btn_smoked: "I Smoked...",
		auth_error_no_profile: "Login successful, but profile data is missing.",
		// Context selection
		context_modal_title: "What's triggering you?",
		context_modal_subtitle: "Help me understand the situation",
		context_coffee: "Coffee Break",
		context_alcohol: "Social/Drinks",
		context_stress: "Stress/Work",
		context_boredom: "Boredom/Sadness",
		context_meal: "After Meal",
	},
	it: {
		welcome: "Benvenuto su Respira",
		onboarding_q1: "Quante sigarette fumi al giorno?",
		onboarding_q2: "Quanto costa un pacchetto?",
		onboarding_q3: "Quante sigarette ci sono in un pacchetto?",
		onboarding_q4:
			"Qual è il tuo sogno o obiettivo che vuoi realizzare con i soldi risparmiati?",
		onboarding_q5: "Quanto costa questo sogno?",
		onboarding_dream_placeholder:
			"es. Viaggio in Giappone, una nuova chitarra...",
		onboarding_dream_cost_placeholder: "Costo approssimativo",
		cta_start: "Inizia il percorso",
		cta_next: "Avanti",
		dashboard_title: "Il Tuo Progresso",
		money_saved: "Soldi Risparmiati",
		cigs_not_smoked: "Sigarette Evitate",
		time_passed: "Tempo Senza Fumo",
		dream_progress: "Progresso verso il tuo sogno",
		craving_button: "Ho voglia di fumare!",
		craving_loading: "Analizzando la tua forza...",
		craving_modal_title: "Aspetta! Leggi questo...",
		days: "Giorni",
		hours: "h",
		minutes: "m",
		seconds: "s",
		congrats: "Stai andando alla grande!",
		history_chart: "Previsione Risparmi (30 Giorni)",
		lapsed_button: "Ho fumato",
		lapse_modal_title: "È solo un intoppo",
		lapse_modal_text:
			"Non essere severo con te stesso. Un errore non è un fallimento. Ricorda il tuo sogno: {dream}. È ancora lì che ti aspetta. Vogliamo far ripartire l'orologio e continuare?",
		lapse_confirm: "Sì, ricominciamo",
		lapse_cancel: "Annulla",
		auth_register_title: "Crea Account",
		auth_login_title: "Accedi",
		auth_email: "Email",
		auth_password: "Password",
		auth_have_account: "Hai già un account? Accedi",
		auth_no_account: "Nuovo utente? Inizia il percorso",
		auth_login_btn: "Accedi",
		auth_register_btn: "Registrati e Salva i Progressi",
		auth_error_not_found: "Account non trovato o password errata.",
		auth_error_exists: "Un account con questa email esiste già.",
		auth_save_progress: "Salva i tuoi progressi per raggiungere il tuo sogno",
		logout: "Esci",
		// New keys
		urge_modal_title: "Quanto è forte la voglia?",
		urge_rating_label: "Vota da 1 a 10",
		urge_low_title: "È solo noia",
		urge_low_text:
			"Non ne hai bisogno. La voglia passerà in 10 minuti. Aspettiamo insieme.",
		urge_high_title: "Allarme Rosso ⚠️",
		urge_high_text:
			"Se fumi, ti costerà {cost} e allontanerà il sogno '{dream}'.",
		urge_btn_analyze: "Analizza Voglia",
		urge_btn_resisted: "Ho Resistito!",
		urge_btn_smoked: "Ho Fumato...",
		auth_error_no_profile:
			"Accesso riuscito, ma i dati del profilo sono mancanti.",
		// Context selection
		context_modal_title: "Cosa ti sta spingendo?",
		context_modal_subtitle: "Aiutami a capire la situazione",
		context_coffee: "Pausa Caffè",
		context_alcohol: "Sociale/Alcol",
		context_stress: "Stress/Lavoro",
		context_boredom: "Noia/Tristezza",
		context_meal: "Dopo Pasto",
	},
};
